"""add_approval_version

Revision ID: 2e95375b04bf
Revises: 48c281aacec4
Create Date: 2026-06-23 04:09:54.646989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e95375b04bf'
down_revision: Union[str, Sequence[str], None] = '48c281aacec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('version', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.drop_constraint(op.f('uq_approval_listing_type'), 'approvals', type_='unique')
    op.add_column('listings', sa.Column('approval_version', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'approval_version')
    op.create_unique_constraint(op.f('uq_approval_listing_type'), 'approvals', ['listing_id', 'approval_type'], postgresql_nulls_not_distinct=False)
    op.drop_column('approvals', 'version')
    # ### end Alembic commands ###
