"""initial_schema

Revision ID: 8c6659e7e625
Revises: 
Create Date: 2026-06-18 17:29:15.820228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c6659e7e625'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('AGENT', 'APPROVER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('listings',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.Enum('SANG_NHUONG', 'CHO_THUE', 'BAN', name='transactiontype'), nullable=False),
    sa.Column('property_type', sa.Enum('NHA_PHO', 'CAN_HO', 'CHDV', 'DAT', 'BIET_THU', 'VAN_PHONG', 'MAT_BANG', 'KHO_XUONG', 'NHA_TRO', 'KHAC', name='propertytype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('commission_type', sa.Enum('PERCENTAGE', 'FLAT', name='commissiontype'), nullable=False),
    sa.Column('commission_value', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('area_width', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('area_length', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_area', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('num_rooms', sa.Integer(), nullable=False),
    sa.Column('num_bathrooms', sa.Integer(), nullable=False),
    sa.Column('num_floors', sa.Integer(), nullable=False),
    sa.Column('street_name', sa.String(length=255), nullable=False),
    sa.Column('house_number', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('furnishing', sa.String(length=500), nullable=True),
    sa.Column('frontage_type', sa.String(length=100), nullable=True),
    sa.Column('legal_status', sa.String(length=500), nullable=True),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('road_width', sa.String(length=50), nullable=True),
    sa.Column('owner_phone', sa.String(length=20), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'CON_HANG', 'DA_COC', 'DA_CHOT', 'HUY_COC', 'HET_HANG', 'QUA_HAN', name='listingstatus'), nullable=False),
    sa.Column('is_hot', sa.Boolean(), nullable=True),
    sa.Column('hot_order', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.Enum('LISTING', 'APPROVAL', 'DEAL_EVENT', name='referencetype'), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('approval_type', sa.Enum('LISTING_POST', 'DEPOSIT', 'CANCELLATION', 'CLOSURE', 'SOLD_OUT', name='approvaltype'), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', name='decisiontype'), nullable=False),
    sa.Column('decided_by_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal_events',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('DEPOSIT_REPORTED', 'DEPOSIT_CONFIRMED', 'CLOSURE_REPORTED', 'CLOSURE_CONFIRMED', 'CANCELLATION_REPORTED', 'CANCELLATION_CONFIRMED', 'SOLD_OUT_REPORTED', 'SOLD_OUT_CONFIRMED', name='dealeventtype'), nullable=False),
    sa.Column('reported_by_id', sa.UUID(), nullable=False),
    sa.Column('confirmed_by_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('deposit_amount', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_images',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_pins',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'listing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_pins')
    op.drop_table('listing_images')
    op.drop_table('deal_events')
    op.drop_table('approvals')
    op.drop_table('notifications')
    op.drop_table('listings')
    op.drop_table('users')
    # ### end Alembic commands ###
